name: "Pull Request Assignee"
description: "Randomly assigns an assignee to new PRs"
author: "skovati"
on:
  pull_request:
    types:
      - opened
      - ready_for_review
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
inputs:
  token:
    description: >
      "Github auth token for api, automagically grabs the default token
      if none is passed."
    required: false
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "dist/index.js"
