name: "Pull Request Logician"
description: ""
author: "skovati"
inputs:
  token:
    description: >
      "Github auth token for api, automagically grabs the default token
      if none is passed."
    required: false
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "dist/index.js"
