name: "Aerie PR Magic"
on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  aerie-logic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
