name: "Opener Assignee"
on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  assign-opener:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
