name: "Sufficient Approvals"
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize

jobs:
  sufficiency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
