name: "Sufficient Approvals"
on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

jobs:
  sufficiency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
