name: "test"
on:
  pull_request:
    branches:
      - main
    types:
      - opened
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

jobs:
  assign-opener:
    if: github.event.action == "opened"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
  sufficiency-check:
    if: github.event.pull_request_review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
